"""chadd_role_to_users

Revision ID: 23636fad8db2
Revises: 0b080b3a0f94
Create Date: 2026-03-04 13:02:24.587525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23636fad8db2'
down_revision: Union[str, Sequence[str], None] = '0b080b3a0f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column but allow NULL temporarily
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))

    # 2. Set existing users to "user"
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")

    # 3. Make column NOT NULL
    op.alter_column('users', 'role', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
